### ISSUE TITLE
Upgrade to Quarkus 3

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-jackson-jq#75]
Quarkus migration tips: https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x

**Comment by ppalaga** [comment]
It would be great to get a release compatible with recent Quarkus 3.0.0.Alpha3 so that we can test it in Camel Quarkus

**Comment by ricardozanini** [comment]
Hey @ppalaga, I can do it later next week. I'll probably create a new branch to keep Quarkus 2 compatibility and do a different release train.

**Comment by ppalaga** [comment]
Sounds good, thanks @ricardozanini !

**Comment by ppalaga** [comment]
Thanks for taking care! Could we please get an Alpha release, so that we can test with in Camel Quarkus?

**Comment by ricardozanini** [comment]
Yes, we will do an alpha release soon! Thanks @ppalaga!

**Comment by ppalaga** [comment]
Thanks a lot, we integrated 2.0.0.Alpha and it works well.
